setState時に再レンダリングされない
hackathon-21-winter-18/frontend pull request #6
Opened 2021-12-05 13:46 UTC by mehm8128

子コンポーネントから親コンポーネントのstateを変えるのをやってみたのですが、setState時に再レンダリングされず、再レンダリングボタン(適当に作ったbool変数をsetStateで変えるボタン)をクリックすると再レンダリングされます

2021-12-05 15:01 UTC, ucciqun requested changes
レビューしました

2021-12-05 15:01 UTC, ucciqun commented on src/components/Word.tsx
>  	flag: boolean[]
`flag:boolean[]`->`flags:boolean[]`

2021-12-05 15:01 UTC, ucciqun commented on src/components/Word.tsx
>  	setFlag: any
関数型があります。
`setFlag:()=>void`

2021-12-05 15:01 UTC, ucciqun commented on src/components/Word.tsx
> +	function handleClick() {
Wordは親コンポーネントのことなんて気にしてられないので、`handleClick`を受け取ってbuttonが押されたら発火するよう設定するだけの機能を持つほうがわかりやすい。
別のコンポーネントで使われる可能性もあるのだから。

2021-12-05 15:01 UTC, ucciqun commented on src/components/Word.tsx
> -			{wordFlag[num] === false ? (
`hoge===true`とか`hoge===false`は`hoge`、`!hoge`に省略できる。

2021-12-05 15:01 UTC, ucciqun commented on src/components/Word.tsx
> +const Word: React.FC<WordProps> = ({ num, word, flag, setFlag }) => {
`children`がPropsに無いことを明示的に表したいので`React.VFC`を使おう。
詳細は調べてみてください。

2021-12-05 15:01 UTC, ucciqun commented on src/pages/Memorize.tsx
>  	const [samplePalace, setSamplePalace] = useState([
```typescript=
const mockPalaces=[...]
```
のようにモック変数は切り出したほうが可読性高いよ。後は型もつけておきたいですね。
```typescript=
type Palace={ ... }
const  mockPalaces:Palace[]=[...]
```
みたいな感じ。`PalaceType`は別のとこでも使うだろうし、 `types.ts`を別に作ってそこからimportするほうがいいかもね。

2021-12-05 15:01 UTC, ucciqun commented on src/pages/Memorize.tsx
> +			{flag.every((value) => value === true) ? (
ここも`value? :`で書けますよ。一応。

2021-12-06 05:23 UTC, mehm8128 commented on src/pages/Memorize.tsx
>  	const [samplePalace, setSamplePalace] = useState([
他のレビューは理解して修正できたのですが、これだけ分かりません。
モック変数というのは一時的にサンプルとして入れてるデータですよね。
それで、可読性のために別のファイルに切り出した方がいいのも分かります。
そこまでは分かったのですが、具体的にコードをどのように書けばいいのかが分かりません（types.tsの書き方など）
もし時間あれば代わりに書いていただいて、pushしていただけませんか。

2021-12-06 06:20 UTC, merged